// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"database/sql"
)

type AnnotationsCache struct {
	ID            string         `json:"id"`
	UserID        string         `json:"user_id"`
	EbookID       string         `json:"ebook_id"`
	LocationStart string         `json:"location_start"`
	LocationEnd   string         `json:"location_end"`
	HighlightText sql.NullString `json:"highlight_text"`
	Note          sql.NullString `json:"note"`
	Color         sql.NullString `json:"color"`
	RowVersion    int64          `json:"row_version"`
	DeletedAt     sql.NullString `json:"deleted_at"`
	UpdatedAt     string         `json:"updated_at"`
}

type BookmarksCache struct {
	ID         string         `json:"id"`
	UserID     string         `json:"user_id"`
	EbookID    string         `json:"ebook_id"`
	Location   string         `json:"location"`
	Label      sql.NullString `json:"label"`
	RowVersion int64          `json:"row_version"`
	DeletedAt  sql.NullString `json:"deleted_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type BorrowsCache struct {
	ID         string         `json:"id"`
	ShareID    string         `json:"share_id"`
	UserID     string         `json:"user_id"`
	Status     string         `json:"status"`
	ExpiresAt  sql.NullString `json:"expires_at"`
	RowVersion int64          `json:"row_version"`
	DeletedAt  sql.NullString `json:"deleted_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type EbooksCache struct {
	ID         string         `json:"id"`
	Title      string         `json:"title"`
	Author     sql.NullString `json:"author"`
	Format     sql.NullString `json:"format"`
	FilePath   sql.NullString `json:"file_path"`
	RowVersion int64          `json:"row_version"`
	DeletedAt  sql.NullString `json:"deleted_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ReadingProgressCache struct {
	ID              string          `json:"id"`
	UserID          string          `json:"user_id"`
	EbookID         string          `json:"ebook_id"`
	Location        string          `json:"location"`
	ProgressPercent sql.NullFloat64 `json:"progress_percent"`
	ReadingMode     string          `json:"reading_mode"`
	RowVersion      int64           `json:"row_version"`
	DeletedAt       sql.NullString  `json:"deleted_at"`
	UpdatedAt       string          `json:"updated_at"`
}

type SessionState struct {
	ID           int64          `json:"id"`
	AccessToken  string         `json:"access_token"`
	RefreshToken string         `json:"refresh_token"`
	UserID       sql.NullString `json:"user_id"`
	UpdatedAt    string         `json:"updated_at"`
}

type ShareReportsCache struct {
	ID         string         `json:"id"`
	ShareID    string         `json:"share_id"`
	ReporterID string         `json:"reporter_id"`
	Reason     string         `json:"reason"`
	Details    sql.NullString `json:"details"`
	RowVersion int64          `json:"row_version"`
	DeletedAt  sql.NullString `json:"deleted_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type ShareReviewsCache struct {
	ID         string         `json:"id"`
	ShareID    string         `json:"share_id"`
	UserID     string         `json:"user_id"`
	Rating     sql.NullInt64  `json:"rating"`
	Review     sql.NullString `json:"review"`
	RowVersion int64          `json:"row_version"`
	DeletedAt  sql.NullString `json:"deleted_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type SharesCache struct {
	ID          string         `json:"id"`
	EbookID     string         `json:"ebook_id"`
	OwnerID     string         `json:"owner_id"`
	Status      string         `json:"status"`
	Title       sql.NullString `json:"title"`
	BorrowUntil sql.NullString `json:"borrow_until"`
	RowVersion  int64          `json:"row_version"`
	DeletedAt   sql.NullString `json:"deleted_at"`
	UpdatedAt   string         `json:"updated_at"`
}

type SyncCheckpoint struct {
	ID                  int64          `json:"id"`
	LastServerTimestamp sql.NullString `json:"last_server_timestamp"`
	LastEventID         sql.NullString `json:"last_event_id"`
	UpdatedAt           string         `json:"updated_at"`
}

type SyncEventsOutbox struct {
	ID             string         `json:"id"`
	EntityType     string         `json:"entity_type"`
	EntityID       string         `json:"entity_id"`
	Operation      string         `json:"operation"`
	PayloadJson    sql.NullString `json:"payload_json"`
	BaseVersion    sql.NullInt64  `json:"base_version"`
	IdempotencyKey string         `json:"idempotency_key"`
	Status         string         `json:"status"`
	AttemptCount   int64          `json:"attempt_count"`
	NextAttemptAt  string         `json:"next_attempt_at"`
	LastError      sql.NullString `json:"last_error"`
	CreatedAt      string         `json:"created_at"`
	UpdatedAt      string         `json:"updated_at"`
}

type UserPreferencesCache struct {
	UserID             string `json:"user_id"`
	ReadingMode        string `json:"reading_mode"`
	ZenRestoreOnOpen   int64  `json:"zen_restore_on_open"`
	ThemeMode          string `json:"theme_mode"`
	ThemeOverridesJson string `json:"theme_overrides_json"`
	TypographyProfile  string `json:"typography_profile"`
	RowVersion         int64  `json:"row_version"`
	UpdatedAt          string `json:"updated_at"`
}

type UserReaderStateCache struct {
	UserID          string         `json:"user_id"`
	CurrentEbookID  sql.NullString `json:"current_ebook_id"`
	CurrentLocation sql.NullString `json:"current_location"`
	ReadingMode     string         `json:"reading_mode"`
	RowVersion      int64          `json:"row_version"`
	LastOpenedAt    sql.NullString `json:"last_opened_at"`
	UpdatedAt       string         `json:"updated_at"`
}
