// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	ClearSessionState(ctx context.Context) error
	EnqueueSyncOutboxEvent(ctx context.Context, arg EnqueueSyncOutboxEventParams) error
	GetSessionState(ctx context.Context) (*GetSessionStateRow, error)
	GetSyncCheckpoint(ctx context.Context) (*GetSyncCheckpointRow, error)
	GetUISettings(ctx context.Context) (*GetUISettingsRow, error)
	GetUserPreferencesCache(ctx context.Context, userID string) (*UserPreferencesCache, error)
	GetUserReaderStateCache(ctx context.Context, userID string) (*UserReaderStateCache, error)
	ListActiveEbooksCache(ctx context.Context) ([]*EbooksCache, error)
	ListActiveSharesCache(ctx context.Context) ([]*SharesCache, error)
	ListPendingSyncOutboxEvents(ctx context.Context, arg ListPendingSyncOutboxEventsParams) ([]*SyncEventsOutbox, error)
	MarkSyncOutboxEventRetry(ctx context.Context, arg MarkSyncOutboxEventRetryParams) error
	MarkSyncOutboxEventSucceeded(ctx context.Context, arg MarkSyncOutboxEventSucceededParams) error
	SearchActiveEbooksCache(ctx context.Context, searchTerm string) ([]*EbooksCache, error)
	UpsertEbookCache(ctx context.Context, arg UpsertEbookCacheParams) error
	UpsertSessionState(ctx context.Context, arg UpsertSessionStateParams) error
	UpsertShareCache(ctx context.Context, arg UpsertShareCacheParams) error
	UpsertSyncCheckpoint(ctx context.Context, arg UpsertSyncCheckpointParams) error
	UpsertUISettings(ctx context.Context, arg UpsertUISettingsParams) error
	UpsertUserPreferencesCache(ctx context.Context, arg UpsertUserPreferencesCacheParams) error
	UpsertUserReaderStateCache(ctx context.Context, arg UpsertUserReaderStateCacheParams) error
}

var _ Querier = (*Queries)(nil)
